CREATE TABLE venues (
                        id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        code     VARCHAR(100) NOT NULL,
                        name     VARCHAR(150) NOT NULL,
                        city     VARCHAR(100) NOT NULL,
                        address  VARCHAR(200) NOT NULL,
                        capacity INTEGER      NOT NULL,
                        active   BOOLEAN      NOT NULL DEFAULT TRUE,

                        CONSTRAINT PK_venues_id PRIMARY KEY (id),
                        CONSTRAINT UQ_venues_code UNIQUE (code),
                        CONSTRAINT CHK_venues_capacity CHECK (capacity > 0)
);

CREATE TABLE events (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        venue_id    BIGINT       NOT NULL,
                        event_code  VARCHAR(100) NOT NULL,
                        name        VARCHAR(150) NOT NULL,
                        description TEXT,
                        category    VARCHAR(30)  NOT NULL,
                        status      VARCHAR(30)  NOT NULL,
                        event_date  TIMESTAMP    NOT NULL,
                        minimum_age INTEGER      NOT NULL,

                        CONSTRAINT PK_events_id PRIMARY KEY (id),
                        CONSTRAINT FK_events_venue_id FOREIGN KEY (venue_id) REFERENCES venues(id),
                        CONSTRAINT UQ_events_event_code UNIQUE (event_code),
                        CONSTRAINT CHK_events_category CHECK (category IN
                                                              ('MUSIC', 'SPORTS', 'TECHNOLOGY', 'EDUCATION', 'CULTURE', 'ENTERTAINMENT')),
                        CONSTRAINT CHK_events_status CHECK (status IN
                                                            ('DRAFT', 'PUBLISHED', 'SOLD_OUT', 'CANCELLED', 'FINISHED')),
                        CONSTRAINT CHK_events_minimum_age CHECK (minimum_age >= 0)
);

CREATE TABLE artists (
                         id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         stage_name VARCHAR(150) NOT NULL,
                         country    VARCHAR(100) NOT NULL,
                         genre      VARCHAR(100) NOT NULL,
                         active     BOOLEAN      NOT NULL DEFAULT TRUE,

                         CONSTRAINT PK_artists_id PRIMARY KEY (id),
                         CONSTRAINT UQ_artists_stage_name UNIQUE (stage_name)
);

CREATE TABLE event_artists (
                               event_id  BIGINT NOT NULL,
                               artist_id BIGINT NOT NULL,

                               CONSTRAINT PK_event_artists_id PRIMARY KEY (event_id, artist_id),
                               CONSTRAINT FK_event_artists_event_id FOREIGN KEY (event_id) REFERENCES events(id),
                               CONSTRAINT FK_event_artists_artist_id FOREIGN KEY (artist_id) REFERENCES artists(id)
);

CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       username VARCHAR(100) NOT NULL,
                       email    VARCHAR(200) NOT NULL,
                       active   BOOLEAN      NOT NULL DEFAULT TRUE,

                       CONSTRAINT PK_users_id PRIMARY KEY (id),
                       CONSTRAINT UQ_users_username UNIQUE (username),
                       CONSTRAINT UQ_users_email UNIQUE (email)
);

CREATE TABLE user_profiles (
                               id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               user_id    BIGINT       NOT NULL,
                               first_name VARCHAR(150) NOT NULL,
                               last_name  VARCHAR(150) NOT NULL,
                               phone      VARCHAR(30),
                               city       VARCHAR(100),
                               birth_date DATE,

                               CONSTRAINT PK_user_profiles_id PRIMARY KEY (id),
                               CONSTRAINT FK_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id),
                               CONSTRAINT UQ_user_profiles_user_id UNIQUE (user_id)
);

CREATE TABLE tickets (
                         id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         user_id       BIGINT         NOT NULL,
                         event_id      BIGINT         NOT NULL,
                         ticket_code   VARCHAR(100)   NOT NULL,
                         type          VARCHAR(30)    NOT NULL,
                         price         NUMERIC(12, 2) NOT NULL,
                         status        VARCHAR(30)    NOT NULL,
                         purchase_date TIMESTAMP      NOT NULL,

                         CONSTRAINT PK_tickets_id PRIMARY KEY (id),
                         CONSTRAINT FK_tickets_user_id FOREIGN KEY (user_id) REFERENCES users(id),
                         CONSTRAINT FK_tickets_event_id FOREIGN KEY (event_id) REFERENCES events(id),
                         CONSTRAINT UQ_tickets_ticket_code UNIQUE (ticket_code),
                         CONSTRAINT CHK_tickets_price CHECK (price >= 0),
                         CONSTRAINT CHK_tickets_type CHECK (type IN ('GENERAL', 'VIP', 'BACKSTAGE', 'STUDENT')),
                         CONSTRAINT CHK_tickets_status CHECK (status IN ('RESERVED', 'PAID', 'CANCELLED', 'USED'))
);

CREATE INDEX idx_venues_city
    ON venues(city);

CREATE INDEX idx_events_venue
    ON events(venue_id);

CREATE INDEX idx_events_status
    ON events(status);

CREATE INDEX idx_events_event_date
    ON events(event_date);

CREATE INDEX idx_event_artists_artist
    ON event_artists(artist_id);

CREATE INDEX idx_tickets_user
    ON tickets(user_id);

CREATE INDEX idx_tickets_event
    ON tickets(event_id);

CREATE INDEX idx_tickets_status
    ON tickets(status);